package com.example.bookinventoryapp.ui

import androidx.lifecycle.ViewModel
import com.example.bookinventoryapp.book.data.HomePageUiState
import com.example.bookinventoryapp.book.domain.Book
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.time.LocalDate

class HomeScreenViewModel : ViewModel() {

    private val _uiState = MutableStateFlow(HomePageUiState(books = getBooks(null)))
    val uiState: StateFlow<HomePageUiState> = _uiState.asStateFlow()


    //TODO : Fix model for actual use
    fun getBooks(imageByteArray: ByteArray?): List<Book> {
        if (imageByteArray == null || imageByteArray.isEmpty()) {
            return emptyList()
        }
        val books = listOf(
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = true,
                isOnWishlist = false,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = true,
                isOnWishlist = false,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = true,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = true,
                isOnWishlist = false,
                notes = null
            ),
            Book(
                "NRWPDQAAQBAJ",
                "Chocolate War",
                "123456789",
                listOf("Robert Cormier"),
                summary = "Summary",
                coverByteArray = imageByteArray,
                isbn13 = "9780375829871",
                isbn10 = "0375829873",
                publisher = "Ember",
                publishedDate = LocalDate.of(2024, 9, 14),
                pageCount = 274,
                categories = listOf("Young Adult Fiction"),
                coverUri = "http://books.google.com/books/content?id=NRWPDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api",
                isOwned = false,
                isOnWishlist = false,
                notes = null
            )
        )

        return books
    }
}